language: python
python:
  - "3.6"
services:
  - postgresql

before_install:
  psql -c 'create database av_dashboard_test;'  -U postgres

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install .
  - cp alembic.ini.travis alembic.ini
  - alembic upgrade head

# command to run tests
script: ./run_ci.sh
