language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
  # command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install .
  # command to run tests
script: aloe
