language: python
python:
  - "3.6"
node_js: "9.2.0"
services:
  - postgresql

before_install:
  psql -c 'create database av_dashboard_test;'  -U postgres

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install .
  - yarn install
  - npx webpack
  - cp instance/config.py.example instance/config.py
  - cp alembic.ini.example alembic.ini
  - alembic upgrade head --tag ci_db

# command to run tests
script: ./run_ci.sh
