FROM python:3.6

WORKDIR /av_dashboard

COPY . /av_dashboard/
RUN pip3 install -r requirements.txt 
RUN ["chmod", "+x", "docker/entrypoints/docker-entrypoint.sh"]

ENTRYPOINT ["docker/entrypoints/docker-entrypoint.sh"]
CMD ["flask",  "run", "--host=0.0.0.0"]